version: "3.9"

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 Mental_health.asgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CHANNEL_LAYER_HOST=redis
      - CHANNEL_LAYER_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    # internal Docker network uses port 6379 by default
    # no need to expose it to host unless you really want to
    ports:
      - "6380:6379"

  celery:
    build: .
    command: celery -A Mental_health worker -l info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CHANNEL_LAYER_HOST=redis
      - CHANNEL_LAYER_PORT=6379
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A Mental_health beat -l info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - CHANNEL_LAYER_HOST=redis
      - CHANNEL_LAYER_PORT=6379
    depends_on:
      - redis
      - web
